services:
  nginx:
    ports:
      - "80:80"

  frontend:
    build:      
      context: ./frontend/myonitoring    # npm install이 실행되는 폴더
      dockerfile: ../Dockerfile          # Dockerfile의 상대 경로
    volumes:    
      - ./frontend/myonitoring:/app      
      - /app/node_modules

  backend:
    build:      
      context: ./backend
      dockerfile: Dockerfile
    volumes:    
      - ./backend:/app
      - /app/build
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}

  mysql:
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}