services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: myonitoring-nginx:latest 
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

  frontend:
    image: kst1040/myonitoring-frontend:latest
    environment:
      - TZ=Asia/Seoul
    expose:
      - "80"

  backend:
    image: kst1040/myonitoring-backend:latest
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - VITE_KAKAO_API_KEY=${VITE_KAKAO_API_KEY}
      - VITE_KAKAO_REDIRECT_URI=${VITE_KAKAO_REDIRECT_URI}
      - FIREBASE_CONFIG_PATH=${FIREBASE_CONFIG_PATH}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
      - FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
      - FIREBASE_APP_ID=${FIREBASE_APP_ID}
      - FIREBASE_VAPID_KEY=${FIREBASE_VAPID_KEY}
      - FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}
    volumes:
      - ./myonitoring-firebase-adminsdk-fbsvc-78c9791370.json:/app/src/main/resources/firebase-config.json
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    command: 
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --log-timestamps=system
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    ports:
      - "3307:3306"

volumes:
  mysql_data: